version: "3"
services:
    parser:
      build:
        dockerfile: parser.dockerfile
      volumes:
      - ./workspace/data:/workspace/data
    jupyter:
      hostname: jupyter
      container_name: jupyter
      build:
          dockerfile: jupyter.dockerfile
      ports:
      - "8888:8888"
      volumes:
        - ${PWD}/workspace:/notebook
      working_dir: /notebook
      restart: unless-stopped